import type { AppInfo, Destination, Protocol } from "./types";

export const APPS: AppInfo[] = [
  {
    id: "system",
    name: "System",
    exe: "System",
    publisher: "Microsoft Windows",
    signed: true,
    pid: 4,
    category: "system",
    path: "System",
  },
  {
    id: "svchost",
    name: "Service Host",
    exe: "svchost.exe",
    publisher: "Microsoft Windows",
    signed: true,
    pid: 1184,
    category: "system",
    path: "C:\\Windows\\System32\\svchost.exe",
  },
  {
    id: "defender",
    name: "Microsoft Defender",
    exe: "MsMpEng.exe",
    publisher: "Microsoft Corporation",
    signed: true,
    pid: 2460,
    category: "system",
    path: "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\MsMpEng.exe",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    exe: "OneDrive.exe",
    publisher: "Microsoft Corporation",
    signed: true,
    pid: 5312,
    category: "office",
    path: "C:\\Users\\User\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe",
  },
  {
    id: "search",
    name: "Windows Search",
    exe: "SearchHost.exe",
    publisher: "Microsoft Windows",
    signed: true,
    pid: 3908,
    category: "system",
    path: "C:\\Windows\\SystemApps\\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\\SearchHost.exe",
  },
  {
    id: "chrome",
    name: "Google Chrome",
    exe: "chrome.exe",
    publisher: "Google LLC",
    signed: true,
    pid: 4820,
    category: "browser",
    path: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
  },
  {
    id: "edge",
    name: "Microsoft Edge",
    exe: "msedge.exe",
    publisher: "Microsoft Corporation",
    signed: true,
    pid: 6104,
    category: "browser",
    path: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
  },
  {
    id: "firefox",
    name: "Firefox",
    exe: "firefox.exe",
    publisher: "Mozilla Corporation",
    signed: true,
    pid: 7740,
    category: "browser",
    path: "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
  },
  {
    id: "discord",
    name: "Discord",
    exe: "Discord.exe",
    publisher: "Discord Inc.",
    signed: true,
    pid: 2104,
    category: "chat",
    path: "C:\\Users\\User\\AppData\\Local\\Discord\\app-1.0.9188\\Discord.exe",
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    exe: "ms-teams.exe",
    publisher: "Microsoft Corporation",
    signed: true,
    pid: 8802,
    category: "chat",
    path: "C:\\Program Files\\WindowsApps\\MSTeams\\ms-teams.exe",
  },
  {
    id: "spotify",
    name: "Spotify",
    exe: "Spotify.exe",
    publisher: "Spotify AB",
    signed: true,
    pid: 3340,
    category: "media",
    path: "C:\\Users\\User\\AppData\\Roaming\\Spotify\\Spotify.exe",
  },
  {
    id: "steam",
    name: "Steam",
    exe: "steam.exe",
    publisher: "Valve Corporation",
    signed: true,
    pid: 1568,
    category: "game",
    path: "C:\\Program Files (x86)\\Steam\\steam.exe",
  },
  {
    id: "code",
    name: "Visual Studio Code",
    exe: "Code.exe",
    publisher: "Microsoft Corporation",
    signed: true,
    pid: 9210,
    category: "util",
    path: "C:\\Users\\User\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  },
  {
    id: "outlook",
    name: "Outlook",
    exe: "OUTLOOK.EXE",
    publisher: "Microsoft Corporation",
    signed: true,
    pid: 4488,
    category: "office",
    path: "C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE",
  },
  {
    id: "zoom",
    name: "Zoom",
    exe: "Zoom.exe",
    publisher: "Zoom Video Communications",
    signed: true,
    pid: 7022,
    category: "chat",
    path: "C:\\Users\\User\\AppData\\Roaming\\Zoom\\bin\\Zoom.exe",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    exe: "WhatsApp.exe",
    publisher: "WhatsApp Inc.",
    signed: true,
    pid: 6401,
    category: "chat",
    path: "C:\\Program Files\\WindowsApps\\5319275A.WhatsAppDesktop\\WhatsApp.exe",
  },
  {
    id: "epic",
    name: "Epic Games Launcher",
    exe: "EpicGamesLauncher.exe",
    publisher: "Epic Games, Inc.",
    signed: true,
    pid: 5088,
    category: "game",
    path: "C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\EpicGamesLauncher.exe",
  },
  {
    id: "riot",
    name: "Riot Client",
    exe: "RiotClientServices.exe",
    publisher: "Riot Games, Inc.",
    signed: true,
    pid: 8122,
    category: "game",
    path: "C:\\Riot Games\\Riot Client\\RiotClientServices.exe",
  },
  {
    id: "nvidia",
    name: "NVIDIA App",
    exe: "NVIDIA App.exe",
    publisher: "NVIDIA Corporation",
    signed: true,
    pid: 2290,
    category: "util",
    path: "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NVIDIA App.exe",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    exe: "Dropbox.exe",
    publisher: "Dropbox, Inc.",
    signed: true,
    pid: 4112,
    category: "office",
    path: "C:\\Program Files (x86)\\Dropbox\\Client\\Dropbox.exe",
  },
  {
    id: "adobe",
    name: "Adobe Updater",
    exe: "AdobeUpdateService.exe",
    publisher: "Adobe Inc.",
    signed: true,
    pid: 1994,
    category: "util",
    path: "C:\\Program Files (x86)\\Common Files\\Adobe\\ARM\\AdobeUpdateService.exe",
  },
  {
    id: "telemetry",
    name: "PC Optimizer",
    exe: "pcopt-svc.exe",
    publisher: "Unbekannt",
    signed: false,
    pid: 13337,
    category: "unknown",
    path: "C:\\Users\\User\\AppData\\Local\\Temp\\pcopt-svc.exe",
  },
  {
    id: "javaupd",
    name: "Java Update Scheduler",
    exe: "jusched.exe",
    publisher: "Oracle Corporation",
    signed: true,
    pid: 2744,
    category: "util",
    path: "C:\\Program Files (x86)\\Common Files\\Java\\Java Update\\jusched.exe",
  },
  {
    id: "rdp",
    name: "Remote Desktop",
    exe: "svchost.exe",
    publisher: "Microsoft Windows",
    signed: true,
    pid: 980,
    category: "system",
    path: "C:\\Windows\\System32\\svchost.exe",
  },
];

export const APP_BY_ID: Record<string, AppInfo> = Object.fromEntries(
  APPS.map((a) => [a.id, a]),
);

export const SYSTEM_APP_IDS = new Set([
  "system",
  "svchost",
  "defender",
  "search",
  "rdp",
]);

const D = (
  host: string,
  ip: string,
  port: number,
  protocol: Protocol,
  country = "US",
): Destination => ({ host, ip, port, protocol, country });

export const DESTINATIONS: Record<string, Destination[]> = {
  system: [
    D("time.windows.com", "20.101.57.9", 123, "NTP", "IE"),
    D("dns.msftncsi.com", "131.107.255.255", 53, "DNS", "US"),
    D("ctldl.windowsupdate.com", "20.190.159.24", 443, "HTTPS", "NL"),
    D("settings-win.data.microsoft.com", "20.190.159.68", 443, "HTTPS", "NL"),
    D("v10.events.data.microsoft.com", "52.182.141.63", 443, "HTTPS", "US"),
  ],
  svchost: [
    D("dns.google", "8.8.8.8", 53, "DNS", "US"),
    D("one.one.one.one", "1.1.1.1", 53, "DNS", "US"),
    D("time.windows.com", "20.101.57.9", 123, "NTP", "IE"),
    D("8.8.8.8", "8.8.8.8", 0, "ICMP", "US"),
    D("1.1.1.1", "1.1.1.1", 0, "ICMP", "US"),
    D("wpad", "192.168.1.1", 80, "HTTP", "LAN"),
    D("239.255.255.250", "239.255.255.250", 1900, "SSDP", "LAN"),
    D("224.0.0.251", "224.0.0.251", 5353, "MDNS", "LAN"),
    D("router.lan", "192.168.1.1", 67, "UDP", "LAN"),
  ],
  defender: [
    D("wdcp.microsoft.com", "20.42.73.24", 443, "HTTPS", "US"),
    D("definitionupdates.microsoft.com", "20.72.235.81", 443, "HTTPS", "US"),
    D("go.microsoft.com", "204.79.197.203", 443, "HTTPS", "US"),
  ],
  onedrive: [
    D("oneclient.sfx.ms", "13.107.4.50", 443, "HTTPS", "NL"),
    D("api.onedrive.com", "13.107.42.12", 443, "HTTPS", "NL"),
    D("storage.live.com", "13.107.42.14", 443, "HTTPS", "IE"),
  ],
  search: [
    D("www.bing.com", "13.107.21.200", 443, "HTTPS", "US"),
    D("api.bing.com", "204.79.197.200", 443, "HTTPS", "US"),
  ],
  chrome: [
    D("www.google.com", "142.250.185.46", 443, "HTTPS", "DE"),
    D("www.youtube.com", "142.250.185.78", 443, "HTTPS", "DE"),
    D("fonts.gstatic.com", "142.250.185.99", 443, "HTTPS", "DE"),
    D("accounts.google.com", "142.250.185.109", 443, "HTTPS", "DE"),
    D("clients4.google.com", "142.250.184.206", 443, "HTTPS", "DE"),
    D("lh3.googleusercontent.com", "142.250.185.33", 443, "HTTPS", "DE"),
    D("www.google.com", "142.250.185.46", 443, "QUIC", "DE"),
    D("safebrowsing.googleapis.com", "142.250.184.234", 443, "HTTPS", "DE"),
    D("redirector.gvt1.com", "142.250.185.14", 80, "HTTP", "DE"),
  ],
  edge: [
    D("www.bing.com", "13.107.21.200", 443, "HTTPS", "US"),
    D("edge.microsoft.com", "20.76.201.171", 443, "HTTPS", "NL"),
    D("msn.com", "13.107.246.40", 443, "HTTPS", "US"),
    D("ntp.msn.com", "13.107.246.10", 443, "HTTPS", "US"),
  ],
  firefox: [
    D("firefox.settings.services.mozilla.com", "34.111.97.67", 443, "HTTPS", "US"),
    D("incoming.telemetry.mozilla.org", "34.120.208.123", 443, "HTTPS", "US"),
    D("location.services.mozilla.com", "34.117.118.44", 443, "HTTPS", "US"),
  ],
  discord: [
    D("discord.com", "162.159.136.234", 443, "HTTPS", "US"),
    D("gateway.discord.gg", "162.159.135.232", 443, "WSS", "US"),
    D("cdn.discordapp.com", "162.159.128.233", 443, "HTTPS", "US"),
    D("us-east1-c1.discord.media", "66.22.196.4", 50001, "UDP", "US"),
    D("status.discord.com", "162.159.128.235", 443, "HTTPS", "US"),
  ],
  teams: [
    D("teams.microsoft.com", "52.113.194.132", 443, "HTTPS", "NL"),
    D("presence.teams.microsoft.com", "52.114.75.24", 443, "HTTPS", "NL"),
    D("worldaz.tr.teams.microsoft.com", "52.114.128.8", 3478, "UDP", "NL"),
  ],
  spotify: [
    D("apresolve.spotify.com", "35.186.224.25", 443, "HTTPS", "US"),
    D("audio-ak.spotify.com", "2.16.184.10", 443, "HTTPS", "DE"),
    D("gew1-spclient.spotify.com", "35.186.224.47", 443, "HTTPS", "DE"),
    D("dealer.spotify.com", "35.186.224.25", 443, "WSS", "US"),
  ],
  steam: [
    D("api.steampowered.com", "208.64.200.45", 443, "HTTPS", "US"),
    D("steamcommunity.com", "23.62.161.27", 443, "HTTPS", "DE"),
    D("cm1.steampowered.com", "162.254.197.181", 27017, "TCP", "NL"),
    D("client-update.steampowered.com", "162.254.192.71", 80, "HTTP", "NL"),
    D("steam-chat.com", "162.254.192.108", 443, "HTTPS", "NL"),
  ],
  code: [
    D("marketplace.visualstudio.com", "13.107.42.18", 443, "HTTPS", "NL"),
    D("update.code.visualstudio.com", "13.107.253.70", 443, "HTTPS", "US"),
    D("default.exp-tas.com", "13.107.246.40", 443, "HTTPS", "US"),
  ],
  outlook: [
    D("outlook.office365.com", "40.99.150.18", 443, "HTTPS", "NL"),
    D("outlook.office.com", "52.96.85.178", 443, "HTTPS", "NL"),
    D("smtp.office365.com", "52.96.109.162", 587, "TCP", "NL"),
  ],
  zoom: [
    D("zoom.us", "170.114.52.2", 443, "HTTPS", "US"),
    D("zoomcrc.com", "3.7.35.16", 8801, "UDP", "DE"),
    D("assets.zoom.us", "13.32.184.42", 443, "HTTPS", "DE"),
  ],
  whatsapp: [
    D("web.whatsapp.com", "157.240.20.53", 443, "HTTPS", "IE"),
    D("g.whatsapp.net", "157.240.20.60", 443, "HTTPS", "IE"),
    D("media-vie1-1.cdn.whatsapp.net", "157.240.27.54", 443, "HTTPS", "AT"),
  ],
  epic: [
    D("launcher-public-service-prod.ol.epicgames.com", "34.194.8.49", 443, "HTTPS", "US"),
    D("epicgames-download1.akamaized.net", "2.16.184.90", 443, "HTTPS", "DE"),
    D("account-public-service-prod.ol.epicgames.com", "52.5.12.77", 443, "HTTPS", "US"),
  ],
  riot: [
    D("clientconfig.rpg.riotgames.com", "104.16.24.9", 443, "HTTPS", "US"),
    D("auth.riotgames.com", "104.16.25.9", 443, "HTTPS", "US"),
    D("europe.gcloud.riotgames.com", "35.244.181.201", 443, "HTTPS", "NL"),
  ],
  nvidia: [
    D("ota-downloads.nvidia.com", "192.229.221.95", 443, "HTTPS", "US"),
    D("api.nvidia.com", "192.229.221.25", 443, "HTTPS", "US"),
  ],
  dropbox: [
    D("client.dropbox.com", "162.125.4.1", 443, "HTTPS", "US"),
    D("dl.dropboxusercontent.com", "162.125.4.15", 443, "HTTPS", "US"),
    D("notify.dropboxapi.com", "162.125.19.131", 443, "WSS", "US"),
  ],
  adobe: [
    D("ccmdl.adobe.com", "193.104.215.60", 443, "HTTPS", "IE"),
    D("lcs-cops.adobe.io", "52.38.146.73", 443, "HTTPS", "US"),
    D("ims-na1.adobelogin.com", "52.6.141.60", 443, "HTTPS", "US"),
  ],
  telemetry: [
    D("collect.pc-optimizer.biz", "185.220.101.47", 443, "HTTPS", "DE"),
    D("cdn.stat-relay.net", "91.219.237.220", 8080, "HTTP", "RU"),
    D("update.grayware-svc.io", "45.133.1.88", 443, "HTTPS", "NL"),
  ],
  javaupd: [
    D("javadl-esd-secure.oracle.com", "23.62.161.80", 443, "HTTPS", "DE"),
    D("java.com", "23.62.161.91", 443, "HTTPS", "DE"),
  ],
  rdp: [
    D("unbekannt-host", "185.220.101.23", 3389, "RDP", "DE"),
    D("scan.shadownet.example", "45.155.205.11", 3389, "RDP", "NL"),
  ],
};

export function destinationsFor(appId: string): Destination[] {
  return DESTINATIONS[appId] ?? DESTINATIONS.chrome!;
}

export function randomOf<T>(list: T[]): T {
  return list[Math.floor(Math.random() * list.length)]!;
}

export const PROMPT_APPS = [
  "chrome",
  "discord",
  "spotify",
  "steam",
  "zoom",
  "epic",
  "riot",
  "telemetry",
  "javaupd",
  "adobe",
  "whatsapp",
  "dropbox",
  "firefox",
] as const;

export const INBOUND_APPS = ["rdp", "svchost"] as const;
